[tool.poetry]
name = "Flunt"
version = "1.0.1"
description = "Python implementation of Domain Notification Pattern based in Flunt (.NET) developed by @andrebaltieri"
authors = ["Emerson Delatorre <38289677+Delatorrea@users.noreply.github.com>"]
repository = "https://github.com/Delatorrea/PyFlunt"
homepage = "https://github.com/Delatorrea/PyFlunt"
documentation = "https://github.com/Delatorrea/PyFlunt"
license = "MIT"
keywords = ["flunt", "domain-notification", "validation", "notification"]
classifiers = ["Topic :: Utilities", "Topic :: Software Development", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11"]
readme = "./README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
faker = "^23.1.0"
pytest = "^6.2.5"
isort = "^5.10.1"
pydocstyle = "^6.1.1"
pytest-cov = "^3.0.0"
mypy = "^0.910"
flake8 = "^4.0.1"
ipdb = "^0.13.9"
ipykernel = "^6.23.1"
taskipy = "^1.11.0"
black = "^23.3.0"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.1.14"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sample = "samples.flunt_sample:main"

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[flake8]
extend-ignore = ["W503", "E501"]
max-line-length = 88

[tool.taskipy.tasks]
lint = "black --check --diff . && isort --check --diff . && flake8 --max-line-length 88 --extend-ignore=W503,E501 . && mypy . && pydocstyle ."
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -x --cov=flunt -vv"
post_test = "coverage html"