name: CD

on:
  pull_request:
      branches: [ main ]

  workflow_dispatch:

jobs:
  executa_build:
    runs-on: ubuntu-latest
    steps:

    - name: Realiza o checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instala Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Instala dependências
      run: poetry install

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.9
      with:
        pypi_token: ${{ secrets.TOKEN_PYPI_PYFLUNT }}
