name: CI

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  executa_black:
    runs-on: ubuntu-latest
    steps:

    - name: Realiza o checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instala dependências
      run: poetry install

    - name: Executa black
      run: poetry run black --check flunt

  executa_isort:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: poetry install

      - name: Executa isort
        run: poetry run isort --profile=black --lines-after-import=2 --check flunt

  executa_pydocstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: poetry install

      - name: Executa pydocstyle
        run: poetry run pydocstyle flunt

  executa_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: poetry install

      - name: Executa test
        run: poetry run pytest
