name: Linters
run-name: ${{ github.actor }} execute Linters 🚀
on:
  pull_request:

  workflow_dispatch:

jobs:
  steps:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Atualiza Pip
        run: python -m pip install --upgrade pip

      - name: Instala dependências
        run: python -m pip install -r requirements_dev.txt

      - name: Executa Ruff
        run: python -m ruff check
