name: Linters
run-name: ${{ github.actor }} execute Linters 🚀
on:
  pull_request:

  workflow_dispatch:

jobs:
  steps:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Atualiza Pip
        run: python -m pip install --upgrade pip

      - name: Instala Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Instala dependências
        run: poetry install

      - name: Inicia environment
        run: poetry shell

      - name: Executa Ruff
        run: ruff check
