name: Realease

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Realiza o checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip install toml

    - name: Read version from pyproject.toml
      id: read-version
      run: |
        version=$(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')
        printf "LITELLM_VERSION=%s" "$version" >> $GITHUB_ENV

    - name: Display version
      run: echo "Current version is $LITELLM_VERSION"

    - name: Create Release
      id: create_release
      uses: joutvhu/create-release@v1
      with:
        tag_name: "v$LITELLM_VERSION"
        name: "Release v$LITELLM_VERSION"
        body: |
          # What's Changed
          - Yml correction for library release and publication and general improvements. by fazedordecodigo in #34
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
