name: Realease

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Realiza o checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip install toml

    - name: Read version from pyproject.toml
      id: read-version
      run: |
        version=$(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')
        printf "LITELLM_VERSION=%s" "$version" >> $GITHUB_ENV

    - name: Display version
      run: echo "Current version is $LITELLM_VERSION"

    - name: Create Release
      id: create_release
      uses: joutvhu/create-release@v1
      with:
        tag_name: v2.1.1
        name: Release v2.1.1
        body: |
          ## [2.1.1] - 2024-02-27
          ### Corrigido
          - Links do README quebrados por @fazedordecodigo em #53
          - Comandos para script de execução do pre-commit por @fazedordecodigo em #53
          - Forma de comunicação para Reportar uma Vulnerabilidade por @fazedordecodigo em #53
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
