name: Realease

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Realiza o checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip install toml

    - name: Read version from pyproject.toml
      id: read-version
      run: |
        version=$(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')
        printf "LITELLM_VERSION=%s" "$version" >> $GITHUB_ENV

    - name: Display version
      run: echo "Current version is $LITELLM_VERSION"

    - name: Create Release
      id: create_release
      uses: joutvhu/create-release@v1
      with:
        tag_name: v2.1.0
        name: Release v2.1.0
        body: |
          ## Adicionado
          - CONTRIBUTING em PT-BR e EN por @fazedordecodigo em #39
          - CODE_OF_CONDUCT em PT-BR e EN por @fazedordecodigo em #40
          - README em PT-BR por @fazedordecodigo em #41
          - CHANGELOG em PT-BR e EN por @fazedordecodigo em #42
          - SECURITY em PT-BR e EN por @fazedordecodigo em #43
          - FUNDING por @fazedordecodigo em #44
          - Pull Request Template em PT-BR por @fazedordecodigo em #45
          - Issue Template Bug Report em PT-BR por @fazedordecodigo em #46
          - Issue Template Feature Report em PT-BR por @fazedordecodigo em #47
          - Issue Template Vulnerability Report em PT-BR por @fazedordecodigo em #48

          ## Corrigido
          - Bug que impedia rodar no python v3.9 por @fazedordecodigo em #36
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
