name: Tests
run-name: ${{ github.actor }} execute Linters 🚀
on:
  pull_request:

  workflow_dispatch:

jobs:
  steps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Atualiza Pip
        run: python -m pip install --upgrade pip

      - name: Instala dependências
        run: pip install tox tox-gh-actions

      - name: Executa Tox
        run: tox

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=fazedordecodigo_PyFlunt
            -Dsonar.organization=fazedordecodigo
            -Dsonar.python.coverage.reportPaths=coverage.xml
